---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache

env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  - EMBER_TRY_SCENARIO=ember-2.8.3
  - EMBER_TRY_SCENARIO=ember-2.4.3
  - EMBER_TRY_SCENARIO=ember-2.3.1
  - EMBER_TRY_SCENARIO=ember-2.2.2
  - EMBER_TRY_SCENARIO=ember-2.0.2
  - EMBER_TRY_SCENARIO=ember-1.13.13
  - EMBER_TRY_SCENARIO=ember-1.13.1

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - npm config set spin false
  - npm install -g bower phantomjs-prebuilt
  - bower --version
  - phantomjs --version

install:
  - npm install
  - bower install

script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup
