---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  - EMBER_TRY_SCENARIO=ember-2.4.3
  - EMBER_TRY_SCENARIO=ember-2.3.1
  - EMBER_TRY_SCENARIO=ember-2.2.2
  - EMBER_TRY_SCENARIO=ember-2.0.2
  - EMBER_TRY_SCENARIO=ember-1.13.13
  - EMBER_TRY_SCENARIO=ember-1.13.1

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - npm install -g phantomjs-prebuilt
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - ember try $EMBER_TRY_SCENARIO test
