name: Node CI

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm i --frozen-lockfile
      - name: lint
        run: pnpm run lint
      - name: test
        run: pnpm run test:ember
      - id: set-matrix
        run: echo "::set-output name=matrix::$(pnpm --silent scenario-tester list --files ./scenarios.js --matrix 'pnpm qunit ./scenarios.js --filter %s:')"
        working-directory: test-app

  compat-scenarios:
    needs: test
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.test.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install --no-lockfile
      - name: test
        run: ${{ matrix.command }}
        working-directory: test-app
